import Footer from 'components/common/layout/footer'
import JobFilter from './list/jobFilter'

const Jobs = () => {
  return (
    <>
      <JobFilter />
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br />
      <Footer />
    </>
  )
}

export default Jobs
