import JobFilter from './list/jobFilter'

const Jobs = () => {
  return (
    <>
      <JobFilter />
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br /> ...
      <br />
    </>
  )
}

export default Jobs
